features:
  selected:
    - 'age'
    - 'gender'
    - 'blood_pressure'
    - 'cholesterol'
    - 'smoking_status'
    - 'family_history'
    - 'physical_activity'
    - 'diet'
    - 'bmi'
    - 'glucose_level'
    - 'education_level'
    - 'employment_status'
    - 'sleep_quality'
    - 'alcohol_consumption'
    - 'medication_use'
    - 'cognitive_assessment_score'
    - 'genetic_marker_presence'
    - 'brain_scan_abnormalities'
    - 'speech_pattern_changes'
    - 'motor_function_tests'
    - 'balance_tests'
    - 'reaction_time_tests'
    - 'memory_tests'
    - 'attention_tests'
    - 'executive_function_tests'
    - 'language_tests'
    - 'visuospatial_tests'
    - 'hearing_tests'
    - 'vision_tests'
    - 'olfactory_tests'
    - 'pain_sensitivity_tests'
    - 'sleep_disorder_history'
    - 'head_injury_history'
    - 'occupational_exposure'
    - 'environmental_exposure'
    - 'social_engagement'
    - 'stress_levels'
    - 'depression_history'
    - 'anxiety_history'
    - 'meditation_practice'
    - 'dietary_supplements'
    - 'vitamin_levels'
    - 'hormone_levels'
    - 'immune_function'
    - 'inflammatory_markers'
    - 'gut_microbiome_composition'
    - 'skin_conductance'
    - 'heart_rate_variability'
    - 'electroencephalogram_patterns'
    - 'functional_mri_patterns'
    - 'cerebrospinal_fluid_biomarkers'
    - 'peripheral_blood_biomarkers'
    - 'genome_wide_association_study_results'
    - 'epigenetic_modifications'
    - 'metabolomics_profiles'
    - 'proteomics_profiles'
    - 'transcriptomics_profiles'
    - 'micro_rna_profiles'
    - 'long_non_coding_rna_profiles'
    - 'telomere_length'
    - 'mitochondrial_function'
    - 'oxidative_stress_levels'
    - 'autophagy_markers'
    - 'synaptic_function_tests'
    - 'neurotransmitter_levels'
    - 'neuroinflammation_markers'
    - 'vascular_health_indicators'
    - 'blood_brain_barrier_integrity'
    - 'white_matter_integrity'
    - 'gray_matter_volume'
    - 'cortical_thickness'
    - 'brain_network_connectivity'
    - 'default_mode_network_activity'
    - 'task_positive_network_activity'
    - 'salience_network_activity'
    - 'cerebellar_function_tests'
    - 'brainstem_function_tests'
    - 'spinal_cord_function_tests'
    - 'peripheral_nervous_system_tests'
    - 'autonomic_nervous_system_tests'
    - 'endocrine_function_tests'
    - 'metabolic_function_tests'
    - 'cardiovascular_function_tests'
    - 'respiratory_function_tests'
    - 'renal_function_tests'
    - 'hepatic_function_tests'
    - 'gastrointestinal_function_tests'
    - 'musculoskeletal_function_tests'
    - 'immune_response_tests'
    - 'allergy_tests'
    - 'infection_history'
    - 'vaccination_history'
    - 'travel_history'
    - 'dietary_habits'
    - 'exercise_routine'
    - 'sleep_patterns'
    - 'social_interactions'
    - 'cognitive_stimulation_activities'
    - 'educational_background'
    - 'occupational_history'
    - 'socioeconomic_status'
    - 'cultural_background'
    - 'language_proficiency'
    - 'literacy_levels'
    - 'numeracy_levels'
    - 'technological_literacy'
    - 'health_literacy'
    - 'access_to_healthcare'
    - 'healthcare_utilization'
    - 'medication_adherence'
    - 'alternative_medicine_use'
    - 'substance_use'
    - 'legal_history'
    - 'military_service'
    - 'trauma_exposure'
    - 'abuse_history'
    - 'neglect_history'
    - 'support_systems'
    - 'caregiver_availability'
    - 'living_arrangements'
    - 'housing_conditions'
    - 'neighborhood_safety'
    - 'community_resources'
    - 'transportation_access'
    - 'dietary_restrictions'
    - 'food_security'
    - 'hydration_status'
    - 'caffeine_consumption'
    - 'nicotine_use'
    - 'illicit_drug_use'
    - 'sexual_health'
    - 'reproductive_history'
    - 'menstrual_history'
    - 'menopause_status'
    - 'andropause_status'
    - 'hormone_replacement_therapy'
    - 'contraceptive_use'
    - 'fertility_treatments'
    - 'pregnancy_history'
    - 'childbirth_history'
    - 'lactation_history'
    - 'parenting_status'
    - 'childhood_development'
    - 'adverse_childhood_experiences'
    - 'education_quality'
    - 'learning_disabilities'
    - 'attention_deficit_disorders'
    - 'autism_spectrum_disorders'
    - 'intellectual_disabilities'
    - 'giftedness'
    - 'creativity_levels'
    - 'artistic_abilities'
    - 'musical_abilities'
    - 'athletic_abilities'
    - 'handedness'
    - 'dominant_eye'
    - 'sensory_processing_issues'
    - 'motor_coordination'
    - 'balance_issues'
    - 'gait_abnormalities'
    - 'tremors'
    - 'seizure_history'
    - 'headaches'
